//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scenes/SampleScene/Player/InputSystem/InputSystem.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputSystem: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputSystem()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputSystem"",
    ""maps"": [
        {
            ""name"": ""Controller"",
            ""id"": ""65b11656-2bef-4eb9-9749-a3b08afc44cd"",
            ""actions"": [
                {
                    ""name"": ""Stick_L"",
                    ""type"": ""Value"",
                    ""id"": ""0187836e-bde0-4512-a8db-d1edf0517ea2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Stick_R"",
                    ""type"": ""Value"",
                    ""id"": ""ecd2dfa4-fe64-43c6-b25e-c75a6a2be2c7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Trigger_L"",
                    ""type"": ""Button"",
                    ""id"": ""fee2044e-0592-4a1c-a302-2f7716ef1bea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Trigger_R"",
                    ""type"": ""Button"",
                    ""id"": ""2beeaaec-e07d-4642-a827-29cdf2a1d546"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button_A"",
                    ""type"": ""Button"",
                    ""id"": ""e546faf1-e13b-47ee-bc6f-6bc764eb28aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button_B"",
                    ""type"": ""Button"",
                    ""id"": ""fac30c31-b24b-434c-8959-aa35268f4778"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button_Y"",
                    ""type"": ""Button"",
                    ""id"": ""5f207096-f335-490d-aa69-a0f106bb7e90"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button_X"",
                    ""type"": ""Button"",
                    ""id"": ""f0001864-82e0-4bc6-b4a9-f153911d772d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dpad_up"",
                    ""type"": ""Button"",
                    ""id"": ""10c289f6-7c35-4ae7-8046-fd0f69b1d87b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dpad_right"",
                    ""type"": ""Button"",
                    ""id"": ""4e7fba86-c1a7-488f-958a-a7341741e524"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dpad_left"",
                    ""type"": ""Button"",
                    ""id"": ""9decd8f3-1f90-4700-a183-0a4fd93493fb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dpad_down"",
                    ""type"": ""Button"",
                    ""id"": ""8a3f0686-024d-4c38-b34b-d4cfc7e184b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button_L"",
                    ""type"": ""Button"",
                    ""id"": ""c293d7c3-aadb-4dfc-9950-d9546f524940"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button_R"",
                    ""type"": ""Button"",
                    ""id"": ""c6f7fcf2-ea28-45f4-b604-08ef0d34720a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stick_L_Press"",
                    ""type"": ""Button"",
                    ""id"": ""81cd61ff-22a7-4c2b-b543-0fce94675b7c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stick_R_Press"",
                    ""type"": ""Button"",
                    ""id"": ""672a372d-69c4-4016-92d9-9a78b5d9248f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""22ac7f79-6d21-48fc-a0be-9982975130cc"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick_L"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88126972-e924-4130-9612-67394012faf9"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick_R"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4adf668d-cdf4-43b0-b497-132e2c519705"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Trigger_L"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0663ef5-091f-4184-9375-157d5b1bdb4d"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Trigger_R"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8fe17ff6-fea3-4b46-ab74-d9372f287be1"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button_A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3bb1280-630f-470d-9f03-c293d5e9b6c5"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button_B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f7423f3-c400-42e3-a3fe-d6023054330f"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button_Y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25964cf5-6c18-49c4-969f-a3f12c6caf1d"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button_X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3e6c7c2-b725-4b7f-b623-5c7396ffea04"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dpad_up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6aee76cb-c853-432b-a048-bd4271d52aca"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dpad_right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a915531-3ae1-4d92-abbd-bced6e2ef245"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dpad_left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62e21baa-c312-494a-90a3-26ef792c9f24"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dpad_down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96c7b6a9-f832-400f-9afd-85e09666f313"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button_L"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df3f7944-9a01-4db7-97d0-4ee8cdc29f45"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button_R"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""313878ce-40a5-4ce4-b0f2-b68738d89c57"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick_L_Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c72d0a3-1037-4260-8e2b-a1b3f48cf860"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick_R_Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Controller
        m_Controller = asset.FindActionMap("Controller", throwIfNotFound: true);
        m_Controller_Stick_L = m_Controller.FindAction("Stick_L", throwIfNotFound: true);
        m_Controller_Stick_R = m_Controller.FindAction("Stick_R", throwIfNotFound: true);
        m_Controller_Trigger_L = m_Controller.FindAction("Trigger_L", throwIfNotFound: true);
        m_Controller_Trigger_R = m_Controller.FindAction("Trigger_R", throwIfNotFound: true);
        m_Controller_Button_A = m_Controller.FindAction("Button_A", throwIfNotFound: true);
        m_Controller_Button_B = m_Controller.FindAction("Button_B", throwIfNotFound: true);
        m_Controller_Button_Y = m_Controller.FindAction("Button_Y", throwIfNotFound: true);
        m_Controller_Button_X = m_Controller.FindAction("Button_X", throwIfNotFound: true);
        m_Controller_Dpad_up = m_Controller.FindAction("Dpad_up", throwIfNotFound: true);
        m_Controller_Dpad_right = m_Controller.FindAction("Dpad_right", throwIfNotFound: true);
        m_Controller_Dpad_left = m_Controller.FindAction("Dpad_left", throwIfNotFound: true);
        m_Controller_Dpad_down = m_Controller.FindAction("Dpad_down", throwIfNotFound: true);
        m_Controller_Button_L = m_Controller.FindAction("Button_L", throwIfNotFound: true);
        m_Controller_Button_R = m_Controller.FindAction("Button_R", throwIfNotFound: true);
        m_Controller_Stick_L_Press = m_Controller.FindAction("Stick_L_Press", throwIfNotFound: true);
        m_Controller_Stick_R_Press = m_Controller.FindAction("Stick_R_Press", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Controller
    private readonly InputActionMap m_Controller;
    private List<IControllerActions> m_ControllerActionsCallbackInterfaces = new List<IControllerActions>();
    private readonly InputAction m_Controller_Stick_L;
    private readonly InputAction m_Controller_Stick_R;
    private readonly InputAction m_Controller_Trigger_L;
    private readonly InputAction m_Controller_Trigger_R;
    private readonly InputAction m_Controller_Button_A;
    private readonly InputAction m_Controller_Button_B;
    private readonly InputAction m_Controller_Button_Y;
    private readonly InputAction m_Controller_Button_X;
    private readonly InputAction m_Controller_Dpad_up;
    private readonly InputAction m_Controller_Dpad_right;
    private readonly InputAction m_Controller_Dpad_left;
    private readonly InputAction m_Controller_Dpad_down;
    private readonly InputAction m_Controller_Button_L;
    private readonly InputAction m_Controller_Button_R;
    private readonly InputAction m_Controller_Stick_L_Press;
    private readonly InputAction m_Controller_Stick_R_Press;
    public struct ControllerActions
    {
        private @InputSystem m_Wrapper;
        public ControllerActions(@InputSystem wrapper) { m_Wrapper = wrapper; }
        public InputAction @Stick_L => m_Wrapper.m_Controller_Stick_L;
        public InputAction @Stick_R => m_Wrapper.m_Controller_Stick_R;
        public InputAction @Trigger_L => m_Wrapper.m_Controller_Trigger_L;
        public InputAction @Trigger_R => m_Wrapper.m_Controller_Trigger_R;
        public InputAction @Button_A => m_Wrapper.m_Controller_Button_A;
        public InputAction @Button_B => m_Wrapper.m_Controller_Button_B;
        public InputAction @Button_Y => m_Wrapper.m_Controller_Button_Y;
        public InputAction @Button_X => m_Wrapper.m_Controller_Button_X;
        public InputAction @Dpad_up => m_Wrapper.m_Controller_Dpad_up;
        public InputAction @Dpad_right => m_Wrapper.m_Controller_Dpad_right;
        public InputAction @Dpad_left => m_Wrapper.m_Controller_Dpad_left;
        public InputAction @Dpad_down => m_Wrapper.m_Controller_Dpad_down;
        public InputAction @Button_L => m_Wrapper.m_Controller_Button_L;
        public InputAction @Button_R => m_Wrapper.m_Controller_Button_R;
        public InputAction @Stick_L_Press => m_Wrapper.m_Controller_Stick_L_Press;
        public InputAction @Stick_R_Press => m_Wrapper.m_Controller_Stick_R_Press;
        public InputActionMap Get() { return m_Wrapper.m_Controller; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ControllerActions set) { return set.Get(); }
        public void AddCallbacks(IControllerActions instance)
        {
            if (instance == null || m_Wrapper.m_ControllerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ControllerActionsCallbackInterfaces.Add(instance);
            @Stick_L.started += instance.OnStick_L;
            @Stick_L.performed += instance.OnStick_L;
            @Stick_L.canceled += instance.OnStick_L;
            @Stick_R.started += instance.OnStick_R;
            @Stick_R.performed += instance.OnStick_R;
            @Stick_R.canceled += instance.OnStick_R;
            @Trigger_L.started += instance.OnTrigger_L;
            @Trigger_L.performed += instance.OnTrigger_L;
            @Trigger_L.canceled += instance.OnTrigger_L;
            @Trigger_R.started += instance.OnTrigger_R;
            @Trigger_R.performed += instance.OnTrigger_R;
            @Trigger_R.canceled += instance.OnTrigger_R;
            @Button_A.started += instance.OnButton_A;
            @Button_A.performed += instance.OnButton_A;
            @Button_A.canceled += instance.OnButton_A;
            @Button_B.started += instance.OnButton_B;
            @Button_B.performed += instance.OnButton_B;
            @Button_B.canceled += instance.OnButton_B;
            @Button_Y.started += instance.OnButton_Y;
            @Button_Y.performed += instance.OnButton_Y;
            @Button_Y.canceled += instance.OnButton_Y;
            @Button_X.started += instance.OnButton_X;
            @Button_X.performed += instance.OnButton_X;
            @Button_X.canceled += instance.OnButton_X;
            @Dpad_up.started += instance.OnDpad_up;
            @Dpad_up.performed += instance.OnDpad_up;
            @Dpad_up.canceled += instance.OnDpad_up;
            @Dpad_right.started += instance.OnDpad_right;
            @Dpad_right.performed += instance.OnDpad_right;
            @Dpad_right.canceled += instance.OnDpad_right;
            @Dpad_left.started += instance.OnDpad_left;
            @Dpad_left.performed += instance.OnDpad_left;
            @Dpad_left.canceled += instance.OnDpad_left;
            @Dpad_down.started += instance.OnDpad_down;
            @Dpad_down.performed += instance.OnDpad_down;
            @Dpad_down.canceled += instance.OnDpad_down;
            @Button_L.started += instance.OnButton_L;
            @Button_L.performed += instance.OnButton_L;
            @Button_L.canceled += instance.OnButton_L;
            @Button_R.started += instance.OnButton_R;
            @Button_R.performed += instance.OnButton_R;
            @Button_R.canceled += instance.OnButton_R;
            @Stick_L_Press.started += instance.OnStick_L_Press;
            @Stick_L_Press.performed += instance.OnStick_L_Press;
            @Stick_L_Press.canceled += instance.OnStick_L_Press;
            @Stick_R_Press.started += instance.OnStick_R_Press;
            @Stick_R_Press.performed += instance.OnStick_R_Press;
            @Stick_R_Press.canceled += instance.OnStick_R_Press;
        }

        private void UnregisterCallbacks(IControllerActions instance)
        {
            @Stick_L.started -= instance.OnStick_L;
            @Stick_L.performed -= instance.OnStick_L;
            @Stick_L.canceled -= instance.OnStick_L;
            @Stick_R.started -= instance.OnStick_R;
            @Stick_R.performed -= instance.OnStick_R;
            @Stick_R.canceled -= instance.OnStick_R;
            @Trigger_L.started -= instance.OnTrigger_L;
            @Trigger_L.performed -= instance.OnTrigger_L;
            @Trigger_L.canceled -= instance.OnTrigger_L;
            @Trigger_R.started -= instance.OnTrigger_R;
            @Trigger_R.performed -= instance.OnTrigger_R;
            @Trigger_R.canceled -= instance.OnTrigger_R;
            @Button_A.started -= instance.OnButton_A;
            @Button_A.performed -= instance.OnButton_A;
            @Button_A.canceled -= instance.OnButton_A;
            @Button_B.started -= instance.OnButton_B;
            @Button_B.performed -= instance.OnButton_B;
            @Button_B.canceled -= instance.OnButton_B;
            @Button_Y.started -= instance.OnButton_Y;
            @Button_Y.performed -= instance.OnButton_Y;
            @Button_Y.canceled -= instance.OnButton_Y;
            @Button_X.started -= instance.OnButton_X;
            @Button_X.performed -= instance.OnButton_X;
            @Button_X.canceled -= instance.OnButton_X;
            @Dpad_up.started -= instance.OnDpad_up;
            @Dpad_up.performed -= instance.OnDpad_up;
            @Dpad_up.canceled -= instance.OnDpad_up;
            @Dpad_right.started -= instance.OnDpad_right;
            @Dpad_right.performed -= instance.OnDpad_right;
            @Dpad_right.canceled -= instance.OnDpad_right;
            @Dpad_left.started -= instance.OnDpad_left;
            @Dpad_left.performed -= instance.OnDpad_left;
            @Dpad_left.canceled -= instance.OnDpad_left;
            @Dpad_down.started -= instance.OnDpad_down;
            @Dpad_down.performed -= instance.OnDpad_down;
            @Dpad_down.canceled -= instance.OnDpad_down;
            @Button_L.started -= instance.OnButton_L;
            @Button_L.performed -= instance.OnButton_L;
            @Button_L.canceled -= instance.OnButton_L;
            @Button_R.started -= instance.OnButton_R;
            @Button_R.performed -= instance.OnButton_R;
            @Button_R.canceled -= instance.OnButton_R;
            @Stick_L_Press.started -= instance.OnStick_L_Press;
            @Stick_L_Press.performed -= instance.OnStick_L_Press;
            @Stick_L_Press.canceled -= instance.OnStick_L_Press;
            @Stick_R_Press.started -= instance.OnStick_R_Press;
            @Stick_R_Press.performed -= instance.OnStick_R_Press;
            @Stick_R_Press.canceled -= instance.OnStick_R_Press;
        }

        public void RemoveCallbacks(IControllerActions instance)
        {
            if (m_Wrapper.m_ControllerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IControllerActions instance)
        {
            foreach (var item in m_Wrapper.m_ControllerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ControllerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ControllerActions @Controller => new ControllerActions(this);
    public interface IControllerActions
    {
        void OnStick_L(InputAction.CallbackContext context);
        void OnStick_R(InputAction.CallbackContext context);
        void OnTrigger_L(InputAction.CallbackContext context);
        void OnTrigger_R(InputAction.CallbackContext context);
        void OnButton_A(InputAction.CallbackContext context);
        void OnButton_B(InputAction.CallbackContext context);
        void OnButton_Y(InputAction.CallbackContext context);
        void OnButton_X(InputAction.CallbackContext context);
        void OnDpad_up(InputAction.CallbackContext context);
        void OnDpad_right(InputAction.CallbackContext context);
        void OnDpad_left(InputAction.CallbackContext context);
        void OnDpad_down(InputAction.CallbackContext context);
        void OnButton_L(InputAction.CallbackContext context);
        void OnButton_R(InputAction.CallbackContext context);
        void OnStick_L_Press(InputAction.CallbackContext context);
        void OnStick_R_Press(InputAction.CallbackContext context);
    }
}
